// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(IrohTransportFFI)
import IrohTransportFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_repoprompt_iroh_transport_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_repoprompt_iroh_transport_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureRepopromptIrohTransportInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol IncomingRequestProtocol: AnyObject, Sendable {

    func close()

    func generation()  -> UInt64

    func pathSummary()  -> String

    func payload()  -> Data

    func peerEndpointId()  -> String

    func respond(payload: Data) async throws

}
open class IncomingRequest: IncomingRequestProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_repoprompt_iroh_transport_fn_clone_incomingrequest(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_repoprompt_iroh_transport_fn_free_incomingrequest(handle, $0) }
    }




open func close()  {try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_incomingrequest_close(
            self.uniffiCloneHandle(),$0
    )
}
}

open func generation() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_incomingrequest_generation(
            self.uniffiCloneHandle(),$0
    )
})
}

open func pathSummary() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_incomingrequest_path_summary(
            self.uniffiCloneHandle(),$0
    )
})
}

open func payload() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_incomingrequest_payload(
            self.uniffiCloneHandle(),$0
    )
})
}

open func peerEndpointId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_incomingrequest_peer_endpoint_id(
            self.uniffiCloneHandle(),$0
    )
})
}

open func respond(payload: Data)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_method_incomingrequest_respond(
                    self.uniffiCloneHandle(),
                    FfiConverterData.lower(payload)
                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_void,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_void,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeTransportError_lift
        )
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIncomingRequest: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = IncomingRequest

    public static func lift(_ handle: UInt64) throws -> IncomingRequest {
        return IncomingRequest(unsafeFromHandle: handle)
    }

    public static func lower(_ value: IncomingRequest) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IncomingRequest {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: IncomingRequest, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIncomingRequest_lift(_ handle: UInt64) throws -> IncomingRequest {
    return try FfiConverterTypeIncomingRequest.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIncomingRequest_lower(_ value: IncomingRequest) -> UInt64 {
    return FfiConverterTypeIncomingRequest.lower(value)
}






public protocol TransportConnectionProtocol: AnyObject, Sendable {

    func close()

    func generation()  -> UInt64

    func pathSummary()  -> String

    func peerEndpointId()  -> String

    func sendFrame(payload: Data) async throws  -> Data

}
open class TransportConnection: TransportConnectionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_repoprompt_iroh_transport_fn_clone_transportconnection(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_repoprompt_iroh_transport_fn_free_transportconnection(handle, $0) }
    }




open func close()  {try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_transportconnection_close(
            self.uniffiCloneHandle(),$0
    )
}
}

open func generation() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_transportconnection_generation(
            self.uniffiCloneHandle(),$0
    )
})
}

open func pathSummary() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_transportconnection_path_summary(
            self.uniffiCloneHandle(),$0
    )
})
}

open func peerEndpointId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_transportconnection_peer_endpoint_id(
            self.uniffiCloneHandle(),$0
    )
})
}

open func sendFrame(payload: Data)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_method_transportconnection_send_frame(
                    self.uniffiCloneHandle(),
                    FfiConverterData.lower(payload)
                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_rust_buffer,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_rust_buffer,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransportConnection: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = TransportConnection

    public static func lift(_ handle: UInt64) throws -> TransportConnection {
        return TransportConnection(unsafeFromHandle: handle)
    }

    public static func lower(_ value: TransportConnection) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransportConnection {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: TransportConnection, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransportConnection_lift(_ handle: UInt64) throws -> TransportConnection {
    return try FfiConverterTypeTransportConnection.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransportConnection_lower(_ value: TransportConnection) -> UInt64 {
    return FfiConverterTypeTransportConnection.lower(value)
}






public protocol TransportEndpointProtocol: AnyObject, Sendable {

    func accept() async throws  -> IncomingConnection

    func acceptRequest() async throws  -> IncomingRequest

    func configuredAlpn()  -> Data

    func connect(addressJson: String, alpn: Data) async throws  -> TransportConnection

    func connectWithPolicy(addressJson: String, alpn: Data, allowRelay: Bool, localOnly: Bool, timeoutMillis: UInt64) async throws  -> TransportConnection

    func shutdown() async throws

    func snapshot() throws  -> EndpointSnapshot

    func waitUntilOnline(timeoutMillis: UInt64) async throws  -> EndpointSnapshot

}
open class TransportEndpoint: TransportEndpointProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_repoprompt_iroh_transport_fn_clone_transportendpoint(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_repoprompt_iroh_transport_fn_free_transportendpoint(handle, $0) }
    }




open func accept()async throws  -> IncomingConnection  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_method_transportendpoint_accept(
                    self.uniffiCloneHandle()

                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_rust_buffer,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_rust_buffer,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeIncomingConnection_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}

open func acceptRequest()async throws  -> IncomingRequest  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_method_transportendpoint_accept_request(
                    self.uniffiCloneHandle()

                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_u64,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_u64,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_u64,
            liftFunc: FfiConverterTypeIncomingRequest_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}

open func configuredAlpn() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_repoprompt_iroh_transport_fn_method_transportendpoint_configured_alpn(
            self.uniffiCloneHandle(),$0
    )
})
}

open func connect(addressJson: String, alpn: Data)async throws  -> TransportConnection  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_method_transportendpoint_connect(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(addressJson),FfiConverterData.lower(alpn)
                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_u64,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_u64,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_u64,
            liftFunc: FfiConverterTypeTransportConnection_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}

open func connectWithPolicy(addressJson: String, alpn: Data, allowRelay: Bool, localOnly: Bool, timeoutMillis: UInt64)async throws  -> TransportConnection  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_method_transportendpoint_connect_with_policy(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(addressJson),FfiConverterData.lower(alpn),FfiConverterBool.lower(allowRelay),FfiConverterBool.lower(localOnly),FfiConverterUInt64.lower(timeoutMillis)
                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_u64,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_u64,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_u64,
            liftFunc: FfiConverterTypeTransportConnection_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}

open func shutdown()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_method_transportendpoint_shutdown(
                    self.uniffiCloneHandle()

                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_void,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_void,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeTransportError_lift
        )
}

open func snapshot()throws  -> EndpointSnapshot  {
    return try  FfiConverterTypeEndpointSnapshot_lift(try rustCallWithError(FfiConverterTypeTransportError_lift) {
    uniffi_repoprompt_iroh_transport_fn_method_transportendpoint_snapshot(
            self.uniffiCloneHandle(),$0
    )
})
}

open func waitUntilOnline(timeoutMillis: UInt64)async throws  -> EndpointSnapshot  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_method_transportendpoint_wait_until_online(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(timeoutMillis)
                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_rust_buffer,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_rust_buffer,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeEndpointSnapshot_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransportEndpoint: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = TransportEndpoint

    public static func lift(_ handle: UInt64) throws -> TransportEndpoint {
        return TransportEndpoint(unsafeFromHandle: handle)
    }

    public static func lower(_ value: TransportEndpoint) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransportEndpoint {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: TransportEndpoint, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransportEndpoint_lift(_ handle: UInt64) throws -> TransportEndpoint {
    return try FfiConverterTypeTransportEndpoint.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransportEndpoint_lower(_ value: TransportEndpoint) -> UInt64 {
    return FfiConverterTypeTransportEndpoint.lower(value)
}




public struct EndpointSnapshot: Equatable, Hashable {
    public let endpointId: String
    public let addressJson: String
    public let generation: UInt64
    public let relayEnabled: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(endpointId: String, addressJson: String, generation: UInt64, relayEnabled: Bool) {
        self.endpointId = endpointId
        self.addressJson = addressJson
        self.generation = generation
        self.relayEnabled = relayEnabled
    }




}

#if compiler(>=6)
extension EndpointSnapshot: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEndpointSnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EndpointSnapshot {
        return
            try EndpointSnapshot(
                endpointId: FfiConverterString.read(from: &buf),
                addressJson: FfiConverterString.read(from: &buf),
                generation: FfiConverterUInt64.read(from: &buf),
                relayEnabled: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: EndpointSnapshot, into buf: inout [UInt8]) {
        FfiConverterString.write(value.endpointId, into: &buf)
        FfiConverterString.write(value.addressJson, into: &buf)
        FfiConverterUInt64.write(value.generation, into: &buf)
        FfiConverterBool.write(value.relayEnabled, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEndpointSnapshot_lift(_ buf: RustBuffer) throws -> EndpointSnapshot {
    return try FfiConverterTypeEndpointSnapshot.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEndpointSnapshot_lower(_ value: EndpointSnapshot) -> RustBuffer {
    return FfiConverterTypeEndpointSnapshot.lower(value)
}


public struct IncomingConnection: Equatable, Hashable {
    public let peerEndpointId: String
    public let generation: UInt64
    public let pathSummary: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(peerEndpointId: String, generation: UInt64, pathSummary: String) {
        self.peerEndpointId = peerEndpointId
        self.generation = generation
        self.pathSummary = pathSummary
    }




}

#if compiler(>=6)
extension IncomingConnection: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIncomingConnection: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IncomingConnection {
        return
            try IncomingConnection(
                peerEndpointId: FfiConverterString.read(from: &buf),
                generation: FfiConverterUInt64.read(from: &buf),
                pathSummary: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: IncomingConnection, into buf: inout [UInt8]) {
        FfiConverterString.write(value.peerEndpointId, into: &buf)
        FfiConverterUInt64.write(value.generation, into: &buf)
        FfiConverterString.write(value.pathSummary, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIncomingConnection_lift(_ buf: RustBuffer) throws -> IncomingConnection {
    return try FfiConverterTypeIncomingConnection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIncomingConnection_lower(_ value: IncomingConnection) -> RustBuffer {
    return FfiConverterTypeIncomingConnection.lower(value)
}


public enum TransportError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Failure(String
    )






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension TransportError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransportError: FfiConverterRustBuffer {
    typealias SwiftType = TransportError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TransportError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Failure(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TransportError, into buf: inout [UInt8]) {
        switch value {





        case let .Failure(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransportError_lift(_ buf: RustBuffer) throws -> TransportError {
    return try FfiConverterTypeTransportError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransportError_lower(_ value: TransportError) -> RustBuffer {
    return FfiConverterTypeTransportError.lower(value)
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureRepopromptIrohTransportInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func endpointIdForSecret(secretKey: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeTransportError_lift) {
    uniffi_repoprompt_iroh_transport_fn_func_endpoint_id_for_secret(
        FfiConverterData.lower(secretKey),$0
    )
})
}
public func startApplicationEndpoint(secretKey: Data, alpn: Data, relayEnabled: Bool, generation: UInt64)async throws  -> TransportEndpoint  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_func_start_application_endpoint(FfiConverterData.lower(secretKey),FfiConverterData.lower(alpn),FfiConverterBool.lower(relayEnabled),FfiConverterUInt64.lower(generation)
                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_u64,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_u64,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_u64,
            liftFunc: FfiConverterTypeTransportEndpoint_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}
public func startEndpoint(secretKey: Data, alpn: Data, relayEnabled: Bool, generation: UInt64)async throws  -> TransportEndpoint  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_repoprompt_iroh_transport_fn_func_start_endpoint(FfiConverterData.lower(secretKey),FfiConverterData.lower(alpn),FfiConverterBool.lower(relayEnabled),FfiConverterUInt64.lower(generation)
                )
            },
            pollFunc: ffi_repoprompt_iroh_transport_rust_future_poll_u64,
            completeFunc: ffi_repoprompt_iroh_transport_rust_future_complete_u64,
            freeFunc: ffi_repoprompt_iroh_transport_rust_future_free_u64,
            liftFunc: FfiConverterTypeTransportEndpoint_lift,
            errorHandler: FfiConverterTypeTransportError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_repoprompt_iroh_transport_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_func_endpoint_id_for_secret() != 42096) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_func_start_application_endpoint() != 5048) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_func_start_endpoint() != 7365) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_incomingrequest_close() != 29022) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_incomingrequest_generation() != 64862) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_incomingrequest_path_summary() != 26950) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_incomingrequest_payload() != 48498) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_incomingrequest_peer_endpoint_id() != 33228) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_incomingrequest_respond() != 7672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportconnection_close() != 47050) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportconnection_generation() != 6480) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportconnection_path_summary() != 17557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportconnection_peer_endpoint_id() != 39718) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportconnection_send_frame() != 25831) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportendpoint_accept() != 32986) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportendpoint_accept_request() != 47478) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportendpoint_configured_alpn() != 38992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportendpoint_connect() != 5372) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportendpoint_connect_with_policy() != 49182) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportendpoint_shutdown() != 19540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportendpoint_snapshot() != 46491) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_repoprompt_iroh_transport_checksum_method_transportendpoint_wait_until_online() != 42315) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureRepopromptIrohTransportInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all